<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="table" params="prefix parent *origin">

    <!-- Constants for robot dimensions -->
    <xacro:property name="table_length" value="3" /> <!-- base (x) of top -->
    <xacro:property name="table_width" value="2" /> <!-- width (y) of top  -->
    <xacro:property name="table_height" value="1" /> <!-- height (z) of top -->
    <xacro:property name="table_thickness" value=".05" /> <!-- height (z) of top -->
    <xacro:property name="leg_length" value="${table_height - table_thickness}" /> <!-- height leg -->
    <xacro:property name="leg_radius" value="0.05" /> <!-- radius of leg -->


  <!-- joint from "world" to "top"-->
  <joint name="{prefix}base_joint" type="fixed">
    <origin rpy="$0 0 0" xyz="0 0 ${table_height}" />
    <parent link="${parent}" />
    <child link="{prefix}top" />
  </joint>

  <!-- Top Link -->
  <link name="{prefix}top">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-table_thickness/2}" />
      <geometry>
        <box size="${table_length} ${table_width} ${table_thickness}" />
      </geometry>
      <material name="brown" />
    </visual>
  </link>

  <!-- joint from "top" to "Leg1"-->
  <joint name="${prefix}leg1_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${(table_length /2) - leg_radius} ${(table_width / 2) - leg_radius} 0" />
    <parent link="{prefix}top" />
    <child link="${prefix}leg1" />
  </joint>

  <!-- Leg1 Link -->
  <link name="${prefix}leg1">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-(table_height + table_thickness) / 2}" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${leg_length}" />
      </geometry>
      <material name="light_grey" />
    </visual>
  </link>

  <!--joint from "top" to "Leg2"-->
  <joint name="${prefix}leg2_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-${(table_length /2) - leg_radius}  ${(table_width / 2) - leg_radius} 0" />
    <parent link="{prefix}top" />
    <child link="${prefix}leg_link_2" />
  </joint>

  <!-- Leg2 Link -->
  <link name="${prefix}leg_link_2">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-(table_height + table_thickness) / 2}" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${leg_length}" />
      </geometry>
      <material name="light_grey" />
    </visual>
  </link>

  <!-- joint from "top" to "leg3"-->
  <joint name="${prefix}leg3_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${(table_length / 2) - leg_radius} -${(table_width / 2) - leg_radius} 0" />
    <parent link="{prefix}top" />
    <child link="${prefix}leg_link_3" />
  </joint>

  <!-- Leg3 Link -->
  <link name="${prefix}leg_link_3">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -${(table_height + table_thickness) / 2}" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${leg_length}" />
      </geometry>
      <material name="light_grey" />
    </visual>
  </link>

  <!-- joint from "top" to "leg4"-->
  <joint name="${prefix}leg4_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-${(table_length /2) - leg_radius} -${(table_width / 2) - leg_radius} 0" />
    <parent link="{prefix}top" />
    <child link="${prefix}leg_link_4" />
  </joint>

  <!-- Leg4 Link -->
  <link name="${prefix}leg_link_4">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -${(table_height + table_thickness) / 2}" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${leg_length}" />
      </geometry>
      <material name="light_grey" />
    </visual>
  </link>

  </xacro:macro>

</robot>