<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="table" params="prefix parent *origin">

    <!-- Constants for robot dimensions -->
    <xacro:property name="table_length" value="2" /> <!-- base (x) of top -->
    <xacro:property name="table_width" value="1" /> <!-- width (y) of top  -->
    <xacro:property name="table_height" value="1" /> <!-- height (z) of top -->
    <xacro:property name="table_thickness" value=".05" /> <!-- height (z) of top -->


  <!-- joint from "world" to "top"-->
  <joint name="${prefix}base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${table_height}" />
    <parent link="${parent}" />
    <child link="${prefix}base_link" />
  </joint>

  <!-- Top Link -->
  <link name="${prefix}base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${-table_thickness/2}" />
      <geometry>
        <box size="${table_length} ${table_width} ${table_thickness}" />
      </geometry>
      <material name="brown" />
    </visual>
  </link>

  </xacro:macro>

</robot>